"""empty message

Revision ID: 821e1dfa64c1
Revises: 68e69b0811a0
Create Date: 2021-05-20 17:51:43.311339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '821e1dfa64c1'
down_revision = '68e69b0811a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('region', sa.Column('vaccinati', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('region', 'vaccinati')
    # ### end Alembic commands ###
